olap:
  vocalization:
    input-manager: console
    text-interpreter: simple
    query-validator: simple
    query-executor: logging
    insight-vocalizator: logging
    insight-vocalization-cost-calculator: words_count
    insight-generator-modules:
      - test